SCREEN_WIDTH = 1020
SCREEN_HEIGHT = 640

GAME_COUNTDOWN = 15

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 4
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_HITLESS_COOLDOWN = 2
PLAYER_LIFE = 2

SHOT_RADIUS = 5